### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by mckuhei** [SuperSodaSea/Omniscent#3]
![image](https://user-images.githubusercontent.com/31839741/147750526-4135ffc3-f547-4f59-a5ff-96c471256faf.png)
![image](https://user-images.githubusercontent.com/31839741/147750532-0ab234b5-d472-41de-b631-efb846c03efb.png)
If use hardware renderer, Star's alpha channel will missing.

**Comment by SuperSodaSea** [comment]
Fixed.
